accounts/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.urls import path,include
from .views import login_view, logout_view, profile_edit_view, profile_view,CustomPasswordChangeView, register_view,profiles_list_page,profile_follow
from django.contrib.auth.views import LoginView,PasswordResetView,PasswordResetDoneView,PasswordResetCompleteView,PasswordResetConfirmView
from django.urls import reverse_lazy
from allauth   import app_settings as allauth_settings

app_name = 'accounts'

urlpatterns = [
    path("login/",LoginView.as_view(),name='login'),
    path("register/",register_view,name='register'),
    path("logout/",logout_view,name='logout'),
    path("profile/<str:username>/",profile_view,name='profile'),
    path("profile/edit/",profile_edit_view,name='profile_edit'),
    path("profiles/",profiles_list_page,name='profiles'),
    ##change password 
    path("password_change/",CustomPasswordChangeView.as_view(success_url=reverse_lazy("accounts:profile")),name='password_change'),
    # path("password_change/done/",PasswordChangeDoneView.as_view(),name='password_change_done'),
    #password reset 
    path("password_reset/",PasswordResetView.as_view(email_template_name='password_reset_email.html',success_url=reverse_lazy("accounts:password_reset_done")),name='password_reset'),
    path("password_reset/done/",PasswordResetDoneView.as_view(),name='password_reset_done'),
    path("reset/<uidb64>/<token>/",PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path("reset/done/",PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

hx_urlpatterns = [
    path("profile/<str:username>/follow/",profile_follow,name='profile_follow'),
]
urlpatterns+=hx_urlpatterns

if allauth_settings.SOCIALACCOUNT_ENABLED:
    pass
    # urlpatterns+= [path("social/",include("allauth.socialaccount.urls"))]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path("accounts/",include("allauth.urls")),
    path("",include("books.urls",namespace='books')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+= path("__reload__/", include("django_browser_reload.urls")),

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

# Create your models here.
User = get_user_model()

def upload_to(instance,filename):
    return "profile/"+instance.user.username+"/"+filename

class Profile(models.Model):
    user = models.OneToOneField(User,unique=True,on_delete=models.CASCADE,related_name='profile')
    image = models.ImageField(upload_to=upload_to,blank=True,null=True)
    date_of_birth = models.DateTimeField(blank=True,null=True)
    following = models.ManyToManyField('self',through='accounts.Contact',related_name='followers',symmetrical=False)

    def __str__(self) -> str:
        return self.user.username 
    def get_absolute_url(self):
        return reverse("accounts:profile",args=[self.user.username])
    
    def get_image_absolute_url(self):
        if self.image:
            return self.image.url
        return None


class Contact(models.Model):
    user_from= models.ForeignKey(Profile,related_name='rel_from_set',on_delete=models.CASCADE)
    user_to  = models.ForeignKey(Profile , related_name='rel_to_set',on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user_from.user.username+" follows " +self.user_to.user.username

    class Meta:
        ordering  = ('-created',)

@receiver(post_save,sender=User)
def create_profile(instance,created,*args, **kwargs):
    if created:
        profile = Profile(user=instance)
        profile.save()

accounts/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as f
from django.contrib.auth.password_validation import validate_password 
from .models import Profile

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserCreationForm(forms.ModelForm):
    password = forms.CharField(validators=[validate_password],widget=forms.PasswordInput)
    re_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username","email"]
    
    def clean_re_password(self):
        cd = self.cleaned_data 
        if cd.get("password") != cd.get("re_password"):
            self.add_error(field="password",error="Password don't match")
            raise forms.ValidationError("Passwords don't match")
        return cd["re_password"]
    def save(self,commit=True,*args, **kwargs):
        cd = self.cleaned_data
        username = cd['username']
        email = cd['email']
        password = cd['password']
        user = User(username=username,email=email)
        user.set_password(password)
        if commit:
            user.save()
        return user


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["date_of_birth","image"]

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget=forms.DateInput(attrs={"class":"input is-primary","type":"date"})
        self.fields['image'].widget=forms.FileInput(attrs={"name":"resume","class":"file-input","type":"file"})
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User 
        fields = ["first_name","last_name"]

accounts/views.py
from re import template
from urllib.request import HTTPRedirectHandler
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.views import PasswordChangeView
from django.contrib import messages
from accounts.models import Contact, Profile
from actions.models import Action
from actions.utils import create_action
from common.decorators import hx_required
from common.http_helpers import is_hx_request
import time

# from helpes.email_generator import email_generator
from .forms import LoginForm, ProfileEditForm,UserCreationForm, UserEditForm


def login_view(request):
    form = LoginForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user and user.is_active:
                login(request, user)
                return HttpResponse("logged in ")
        return HttpResponse("invalid login")

    context = {"form": form}
    return render(request, 'accounts/login.html', context)
def logout_view(request):
    logout(request)
    return redirect(reverse("accounts:login"))
     
def register_view(request):
    form = UserCreationForm(request.POST or None)
    if request.method=="POST":
        if form.is_valid():
            user = form.save()
            return redirect(reverse("accounts:login"))
    context = {
        "form":form,
    }
    return render(request,"registration/register.html",context)

class CustomPasswordChangeView(PasswordChangeView):
    def form_valid(self,form):
        messages.success(self.request,"you password has been changed")
        return super().form_valid(form)

def profiles_list_page(request):
    template_name = 'profile/list.html'
    profiles = Profile.objects.all()
    context = {
        "profiles":profiles
    }
    return render(request,template_name,context)

@login_required
@hx_required
def profile_follow(request,username):
    profile = get_object_or_404(Profile , user__username=username)
    template_name = 'profile/partials/un_follow_btn.html'
    if  profile in request.user.profile.following.all():
        # request.user.profile.following.remove(profile)
        create_action(request.user.profile,f'you are not  following {profile.user.username} anymore',profile)
        Contact.objects.filter(user_from=request.user.profile,user_to=profile).delete()
        template_name='profile/partials/follow_btn.html'
    else:
        create_action(request.user.profile,f'you started following {profile.user.username}',profile)
        Contact.objects.create(user_from=request.user.profile,user_to=profile)
    return render(request,template_name,{})

@login_required
def profile_view(request,username=None):
    template_name = 'profile/detail.html'
    following_ids = request.user.profile.following.values_list('id',flat=True).exclude()
    # actions = Action.objects.exclude(profile__id=request.user.profile.id).filter(profile_id__in=following_ids)[:10]
    actions = Action.objects.filter(profile_id__in=following_ids)[:10]
    actions = actions.select_related("profile","profile__user")
    if username:
        profile = get_object_or_404(Profile,user__username=username)
    else :
        profile = request.user.profile
    context = {
        "profile":profile,
        'actions':actions

    }
    return render(request,template_name,context)


@login_required
def profile_edit_view(request):
    template_name = "profile/edit.html"
    profile_form = ProfileEditForm(instance=request.user.profile)
    user_form = UserEditForm(instance=request.user)
    if request.method=="POST":
        
        profile_form = ProfileEditForm(instance=request.user.profile,data=request.POST  , files=request.FILES  )
        user_form = UserEditForm(instance=request.user,data=request.POST)
        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request,"your profile has been updated successfully")
            return redirect(reverse("accounts:profile"))
    context = {
        "profile_form":profile_form,
        "user_form":user_form
    }
    return render(request,template_name,context)

accounts/templates/profile/detail.html
{% extends 'base.html' %} 
{% block title %} 
{{request.user.username}} profile 
{% endblock title %} 

{% block content %}
<img src="{{profile.get_image_absolute_url}}" width='200px' height='200px' alt="">
<h1 class="">name : {{request.user.username}}</h1>
<h1 class="">email : {{request.user.email}}</h1>
<h1 class="">first name : {{request.user.first_name}}</h1>
<h1 class="">last name : {{request.user.last_name}}</h1>
<h1 class=""> date of birth : {{profile.date_of_birth}}</h1>
<a href="{% url 'accounts:profile_edit' %}">
  <button class="button is-wraning"> edit profile </button>
</a>
<a href="{% url 'accounts:password_change' %}">
  <button class="button is-info">change password</button>
</a>

                    <form method="post"  hx-target="#follow-btns-{{profile.user.username}}"  hx-post="{% url 'accounts:profile_follow' profile.user.username %}"  >
                        {% csrf_token %}
                        <div id="follow-btns-{{profile.user.username}}">
                        {% if  request.user.profile in  profile.followers.all %}
                        {% include 'profile/partials/un_follow_btn.html' %}
                        {% else %}
                        {% include 'profile/partials/follow_btn.html' %}
                        {% endif %}
                        </div>
                    </form>
{% include 'globals/notificatins.html' with actions=actions %}
{% endblock content %}

accounts/templates/profile/edit.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} profile edit
{% endblock title %} {% block content %}
<main class="login-page">
  <form method="post" class="login-form" enctype="multipart/form-data">
    {% csrf_token %} 
    {{  profile_form | crispy }}
    <div class="file">
        <label class="file-label">
            {{profile_form.image}}
          <span class="file-cta">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Choose  an iamge
            </span>
          </span>
        </label>
      </div>
    {{user_form |crispy}}
    <button class="button is-primary">save</button>
    <input type="hidden" name="next" vaue="{{next}}">
    <a href="{% url 'accounts:password_reset' %}">reset my password</a>
  </form>

</main>

{% endblock content %}

accounts/templates/profile/list.html
{% extends 'base.html' %}
{% block title %}
profiles
{% endblock title %}

{% block content %}
<div class=" w-full max-w-screen-lg mx-auto">
    {% for profile in profiles %}
    <div    class="inline-block   z-10 w-64 text-sm font-light text-gray-500 bg-white rounded-lg border border-gray-200 shadow-sm  transition-opacity duration-300 dark:text-gray-400 dark:bg-gray-800 dark:border-gray-600">
        <div class="p-3">
            <div class="flex justify-between items-center mb-2">
                <a href="{{profile.get_absolute_url}}">
                    <img class="w-10 h-10 rounded-full" src="{{profile.get_image_absolute_url}}" alt="no iamge">
                </a>
                <div>
                    <form method="post"  hx-target="#follow-btns-{{profile.user.username}}"  hx-post="{% url 'accounts:profile_follow' profile.user.username %}"  >
                        {% csrf_token %}
                        <div id="follow-btns-{{profile.user.username}}">
                        {% if  request.user.profile in  profile.followers.all %}
                        {% include 'profile/partials/un_follow_btn.html' %}
                        {% else %}
                        {% include 'profile/partials/follow_btn.html' %}
                        {% endif %}
                        </div>
                    </form>
                </div>
            </div>
            <p class="text-base font-semibold leading-none text-gray-900 dark:text-white">
                <a href="{{profile.get_absolute_url}}">{{profile.user.username}}</a>
            </p>
            <p class="mb-3 text-sm font-normal">
                <a href="{{profile.get_absolute_url}}" class="hover:underline">{{profile.user.email}}</a>
            </p>
            <p class="mb-4 text-sm font-light"> {{profile.description}}   </p>
            <ul class="flex text-sm font-light">
                <li class="mr-2">
                    <a href="#" class="hover:underline">
                        <span class="font-semibold text-gray-900 dark:text-white">799</span>
                        <spa>Following</span>
                    </a>
                </li>
                <li>
                    <a href="#" class="hover:underline">
                        <span class="font-semibold text-gray-900 dark:text-white">3,758</span>
                        <span>Followers</span>
                    </a>
                </li>
            </ul>
        </div>
        <div data-popper-arrow></div>
    </div>

    {% endfor %}
    
</div>
{% endblock content %}