books/urls.py
from django.urls import path 
from .views import book_add_view, book_detail_view,books_list_view,book_like
app_name = 'books'

urlpatterns = [
    path('',books_list_view,name='books_list'),
    path('<slug:slug>/',book_detail_view,name='book_detail'),
    path('add/',book_add_view,name='book_add'),
]

hx_urlpatterns = [
    path('<slug:slug>/like/',book_like,name='book_like'),
]

urlpatterns+=hx_urlpatterns

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path("accounts/",include("allauth.urls")),
    path("",include("books.urls",namespace='books')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+= path("__reload__/", include("django_browser_reload.urls")),

templates/base.html
{% load static %}
{% comment %} {% load tailwind_tags %} {% endcomment %}
{% load compress %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/css/output.css' %}">
    {% endcompress %}
    {% comment %} {% tailwind_css %} {% endcomment %}
    <style>
    [x-cloak] { display: none !important; }
    </style>
  </head>

  <body>
    <div class='container max-w-screen-xl  mx-auto'>
      {% include "header.html" %} 
    </div>
      {% block content %} 
      
      {% endblock content %}

    <script src="{% static 'src/js/main.js' %}" type='module' ></script>
    <script src="//unpkg.com/alpinejs" defer></script>
    <script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></script>
    <script src="https://unpkg.com/htmx.org@1.8.2"></script>

  </body>

</html>

templates/header.html
<nav
  class="px-2 py-10 flex flex-col gap-10 bg-white sticky top-0 border-gray-200 dark:bg-gray-900 dark:border-gray-700"
>
  <div class="flex justify-between items-center">
    <div class="flex gap-4 text-sm md:text-base">
      <a
        class="font-bold block bg-light-primary ring-light-primary focus:ring-1 hover:opacity-90 text-white transition-all duration-200 cursor-pointer rounded-sm px-8 py-2"
        >signup</a
      >
      <a
        class="font-bold block hover:bg-light-primary focus:ring-1 ring-light-primary hover:opacity-90 hover:text-white transition-all duration-200 cursor-pointer text-light-primary border border-light-primary rounded-sm px-8 py-2"
        >login</a
      >
    </div>
    <ul class="flex capitalize gap-2   font-medium text-base md:text-xl text-light-primary">
      <li class="px-4  py-2 hover:bg-light-primary rounded-sm     hover:text-white">
        <a href="" class="flex  items-center gap-2  ">
          <svg
            class="w-5 h-5"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="w-6 h-6"
          >
            <path
              fill-rule="evenodd"
              d="M5.625 1.5H9a3.75 3.75 0 013.75 3.75v1.875c0 1.036.84 1.875 1.875 1.875H16.5a3.75 3.75 0 013.75 3.75v7.875c0 1.035-.84 1.875-1.875 1.875H5.625a1.875 1.875 0 01-1.875-1.875V3.375c0-1.036.84-1.875 1.875-1.875zM12.75 12a.75.75 0 00-1.5 0v2.25H9a.75.75 0 000 1.5h2.25V18a.75.75 0 001.5 0v-2.25H15a.75.75 0 000-1.5h-2.25V12z"
              clip-rule="evenodd"
            />
            <path
              d="M14.25 5.25a5.23 5.23 0 00-1.279-3.434 9.768 9.768 0 016.963 6.963A5.23 5.23 0 0016.5 7.5h-1.875a.375.375 0 01-.375-.375V5.25z"
            />
          </svg>

          <span>add a book</span>
        </a>
      </li>
      <li class="px-4  py-2 hover:bg-light-primary rounded-sm     hover:text-white">
        <a href="" class="flex items-center gap-2">

          <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
          </svg>
          

          <span>search </span>
        </a>
      </li>
    </ul>
  </div>
  <div class="flex w-full ">
    <ul class="grid grid-cols-4 font-medium text-light-title text-sm md:text-base w-full  capitalize">
      <li  class="" >
        <a href="{% url 'books:books_list' %}" class="flex p-2 rounded-md transition-all duration-150  hover:bg-light-primary hover:text-white items-center flex-col gap-1 ">
          <svg
            class="h-5 w-5 md:w-6 md:h-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="w-6 h-6"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"
            />
          </svg>

          <span>home</span>
        </a>
      </li>

      <li>
        <a href="" class="flex p-2 rounded-md transition-all duration-150  hover:bg-light-primary hover:text-white items-center flex-col gap-1">
          <svg class="h-5 w-5 md:w-6 md:h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 4.5v15m6-15v15m-10.875 0h15.75c.621 0 1.125-.504 1.125-1.125V5.625c0-.621-.504-1.125-1.125-1.125H4.125C3.504 4.5 3 5.004 3 5.625v12.75c0 .621.504 1.125 1.125 1.125z" />
          </svg>
          

          <span>categories</span>
        </a>
      </li>

      <li>
        <a href="" class="flex p-2 rounded-md transition-all duration-150  hover:bg-light-primary hover:text-white items-center flex-col gap-1">
          <svg class="h-5 w-5 md:w-6 md:h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
          </svg>
          

          <span>authors</span>
        </a>
      </li>

      <li>
        <a href="" class="flex p-2 rounded-md transition-all duration-150  hover:bg-light-primary hover:text-white items-center flex-col gap-1">
          <svg class=" w-5 h-5 md:w-6 md:h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12.75 3.03v.568c0 .334.148.65.405.864l1.068.89c.442.369.535 1.01.216 1.49l-.51.766a2.25 2.25 0 01-1.161.886l-.143.048a1.107 1.107 0 00-.57 1.664c.369.555.169 1.307-.427 1.605L9 13.125l.423 1.059a.956.956 0 01-1.652.928l-.679-.906a1.125 1.125 0 00-1.906.172L4.5 15.75l-.612.153M12.75 3.031a9 9 0 00-8.862 12.872M12.75 3.031a9 9 0 016.69 14.036m0 0l-.177-.529A2.25 2.25 0 0017.128 15H16.5l-.324-.324a1.453 1.453 0 00-2.328.377l-.036.073a1.586 1.586 0 01-.982.816l-.99.282c-.55.157-.894.702-.8 1.267l.073.438c.08.474.49.821.97.821.846 0 1.598.542 1.865 1.345l.215.643m5.276-3.67a9.012 9.012 0 01-5.276 3.67m0 0a9 9 0 01-10.275-4.835M15.75 9c0 .896-.393 1.7-1.016 2.25" />
          </svg>

          <span>most visited</span>
        </a>
      </li>
    </ul>
  </div>
</nav>

{% if messages %} {% for message in messages %} {% include "notification.html"
with title="changed" msg=message %} {% endfor %} {% endif %}

templates/notification.html
  <div class="notification is-primary">
    <button class="delete"></button>
  </div>
  <div class="p-4 mb-4 text-sm text-green-700 bg-green-100 rounded-lg dark:bg-green-200 dark:text-green-800" role="alert">
    <span class="font-medium">notification : </span> 
    {{msg}}
  </div>