books/urls.py
from django.urls import path 
from .views import book_add_view, book_detail_view,books_list_view,book_like
app_name = 'books'

urlpatterns = [
    path('',books_list_view,name='books_list'),
    path('<slug:slug>/',book_detail_view,name='book_detail'),
    path('add/',book_add_view,name='book_add'),
]

hx_urlpatterns = [
    path('<slug:slug>/like/',book_like,name='book_like'),
]

urlpatterns+=hx_urlpatterns

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path("accounts/",include("allauth.urls")),
    path("",include("books.urls",namespace='books')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+= path("__reload__/", include("django_browser_reload.urls")),

books/models.py
from email.policy import default
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save
from django.dispatch import receiver
from random import randint
from django.urls import reverse
from django.utils.text import slugify
from PIL import Image
from accounts.models import Profile
# from cloudinary.models import CloudinaryField


# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length = 150)
    slug = models.SlugField(blank=True)
    description = models.TextField()
    price_in_dz = models.PositiveIntegerField(default=0)
    price_as_str = models.CharField(max_length=150)
    owner  = models.ForeignKey(Profile,related_name='books',on_delete=models.CASCADE)
    likes = models.ManyToManyField(Profile,related_name='liked_books')
    total_likes = models.PositiveIntegerField(default=0,db_index=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    

    def get_absolute_url(self):
        return reverse("books:book_detail",kwargs={"slug": self.slug})


    def __str__(self)->str:
        return self.title
    class Meta:
        ordering = ("-created",)

def upload_image_to(instance,filename)->str:
    return instance.book.owner.user.username+"/books/images/"+filename

class BookImage(models.Model):
    book = models.ForeignKey(Book,related_name="images",on_delete=models.CASCADE)
    alt = models.CharField(max_length=200,blank=True)
    image = models.ImageField(upload_to=upload_image_to)
    # image = CloudinaryField("image")
    created = models.DateTimeField(auto_now_add=True)

    def save(self,*args, **kwargs):
        if not self.alt:
            self.alt = slugify(self.image.name.split(".")[0])
        super().save(*args, **kwargs)

        # if self.image:
        #     img = Image.open(self.image.path)
        #     if img.width >550 or img.height>550:
        #         size=(550,550)
        #         img.thumbnail(size)
        #         img.save(self.image.path)

    def __str__(self):
        return self.alt





@receiver(pre_save,sender=Book)
def generate_slug(instance,*args, **kwargs):
    if not instance.slug:
        extra = str(randint(100,800))
    else:
        extra = instance.slug.split("-")[0]
    instance.slug = slugify(extra+"-"+instance.owner.user.username+'-'+instance.title)
    return instance

books/forms.py
from django import forms 
from .models import Book,BookImage

class BookAddForm(forms.ModelForm):
    class Meta:
        model  = Book
        fields = ['title','description','price_in_dz','price_as_str']
    
    def save(self,commit=True)->Book:
        book = super().save(commit=False)
        if commit:
            book.save()
        return book

class BookImageForm(forms.ModelForm):
    class Meta:
        model  = BookImage
        fields = ['image']
    
    def save(self,commit=True) -> BookImage:
        book_image = super().save(commit)
        if commit:
            book_image.save()
        return book_image

books/views.py
from re import template
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib.auth.decorators import login_required
from actions.utils import create_action
from django.db.models import Count

from common.decorators import hx_required
from common.http_helpers import is_hx_request

from .models import Book
from .forms import BookAddForm,BookImageForm
import redis
from django.conf import settings

r = redis.Redis(host=settings.REDIS_HOST,port=settings.REDIS_PORT,db=settings.REDIS_DB)

# Create your views here.
def books_list_view(request):
    # books = Book.objects.annotate(total_likes=Count("likes")).order_by('-total_likes')
    books = Book.objects.all().order_by("-total_likes")
    template_name = 'books/list.html'
    paginator = Paginator(books,3)
    page = request.GET.get('page')
    try :
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)

    except EmptyPage:
        if is_hx_request(request):
            return HttpResponse("")
        books = paginator.page(paginator.num_pages)
    if is_hx_request(request):
        template_name = 'books/partials/books_list.html'

    context ={
        'books':books
    }
    return render(request,template_name,context)

@login_required
def book_detail_view(request,slug):
    book = get_object_or_404(Book,slug=slug)
    ##increase views
    total_views = r.incr(f"book:{book.id}:views")
    ##increase ranking
    r.zincrby("books_ranking",1,book.id)
    ##getting books by rank
    books_ranking = r.zrange("books_ranking",0,-1,desc=True)[:10]
    books_ranking_ids = [int(id) for id in books_ranking]
    most_visited = list(Book.objects.filter(id__in=books_ranking_ids))
    most_visited.sort(key=lambda x:books_ranking_ids.index(x.id))
    print(most_visited)

    context ={
        'book':book,
        'liked':request.user.profile in book.likes.all(),
        'total_views':total_views
    }
    return render(request,'books/detail.html',context)

def book_add_view(request):
    book_add_form = BookAddForm()
    book_image_form = BookImageForm()

    if request.method=="POST":
        book_add_form = BookAddForm(data=request.POST)
        book_image_form = BookImageForm(files=request.FILES)

        if book_add_form.is_valid() and book_image_form.is_valid():
            book = book_add_form.save(commit=False)
            image = book_image_form.save(commit=False)
            book.owner = request.user.profile 
            image.book = book

            print(book)
            print(image)


            book.save()
            image.save()

    context ={
        'book_add_form':book_add_form,
        'book_image_form':book_image_form
    }
    return render(request,'books/add.html',context)


@hx_required
def book_like(request,slug):
    book = get_object_or_404(Book,slug=slug)
    profile = request.user.profile
    template = 'books/partials/like.html'
    if profile in book.likes.all():
        create_action(profile,f"you disliked this book '{book.title}' ",book)
        book.likes.remove(profile)
    else:
        book.likes.add(profile)
        create_action(profile,f"you liked this book '{book.title}' ",book)
        template = 'books/partials/dislike.html'
    return render(request,template)

books/templates/books/add.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} add a
book {% endblock %} {% block content %}
<div class="">
  <form method="POST" enctype="multipart/form-data">
    {{book_add_form | crispy}} {{book_image_form | crispy}} {% csrf_token %}
    <button class="button is-primary">add</button>
  </form>
</div>
{% endblock content %}

books/templates/books/detail.html
{% extends 'base.html' %} 
{% block title %} {{book.title}} {% endblock title %}
{% block content  %}
<div>

  <div>
   {{book.title}}
  </div>
  <div>
    {{book.description}} 
  </div>
  <div>
    {{book.price_in_dz}}
  </div>
  <div>
  {{book.price_as_str}} 
  </div>
  <div>
    views :{{total_views}}

  </div>
  {% for image in books.images.all %}
  <img src="{{image.image.url}}" alt="{{image.alt}}" />
  {% endfor %} {% comment %} like add remove {% endcomment %}

  {% comment %} <div data-slug="{{book.slug}}" x-data="{liked:('{{liked}}'=='True'),addLike(){
  } }"  x-cloak> {% endcomment %}
  <form
      hx-post="{% url 'books:book_like' book.slug %}"
      hx-target="#like-btns"
      >
      {% csrf_token %}
  <div  id='like-btns'>
      {% if liked %}
      {% include 'books/partials/dislike.html' %}
      {% else %}
      {% include 'books/partials/like.html' %}
      {% endif %}
  </div>
  </form>
</div>
{% endblock content %}

books/templates/books/list.html
{% extends 'base.html' %} 
{% block title %} 
books 
{% endblock title %} 

{% block content %} 

<section class="w-full  px-2  h-72 flex flex-col justify-center items-center ">
    <form action="/search" method="GET" class="w-full  max-w-screen-sm ">   
        <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300">Search</label>
        <div class="relative rounded-full ">
            <div class="flex absolute     inset-y-0 left-0 items-center pl-3 pointer-events-none">
                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
            </div>
            <input name="q" type="search" id="default-search " class="block  font-medium  p-4 md:py-6 pl-10 w-full  text-gray-900 bg-gray-50 rounded-full border border-gray-300 focus:ring-light-primary focus:border-light-primary  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white   " placeholder="Search ..." required>
            <button type="submit" class="text-white  absolute right-4 bottom-2 md:bottom-4 bg-light-primary  hover:opacity-90 ring-light-primary focus:ring-2 focus:outline-none  font-medium rounded-full text-sm px-4 py-2 md:px-5 md:py-3    ">Search</button>
        </div>
    </form>

</section>
<div class="container   max-w-screen-xl mx-auto">
<div class="flex w-full items-start    justify-between ">

<div class="bg-gray-100 hidden md:flex rounded-md w-64    py-4    flex-col gap-4  ">
    <div class="flex flex-col gap-3 px-2  ">
        <div class="w-full  bg-gray-200 text-light-primary py-3 px-3 rounded-md ">
        <h3 class=" capitalize font-medium  ">categories</h3>
        </div>
        <ul class="flex flex-col gap-1">
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <button class="w-full bg-light-primary hover:opacity-90 text-white rounded-md cursor-pointer py-2 my-2">all categories</button>
        </ul>

    </div>
    <div class="flex flex-col gap-2">
        <div class="w-full bg-gray-200 text-light-primary py-3 px-3 rounded-md ">
        <h3 class=" capitalize font-medium ">authors</h3>
        </div>
        <ul class="flex flex-col gap-1 px-1 ">
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <li class="cursor-pointer hover:bg-gray-200 hover:text-light-primary font-medium capitalize  text-light-title px-2 py-1 rounded-md">algeria </li>
            <button class="w-full bg-light-primary hover:opacity-90 text-white rounded-md cursor-pointer py-2 my-2">all authors </button>
        </ul>

    </div>

</div>
<div class="w-full max-w-screen-lg gap-2 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4  px-2  ">
{% include 'books/partials/books_list.html' with books=books %}

</div>
</div>
</div>

{% endblock content %}